### ISSUE TITLE
Casting a MIPS pointer to a capability function pointer appears to derive the capability from $c0 instead of $pcc

### ISSUE THREAD

**Issue by rwatson** [CTSRD-CHERI/clang#70] opened 2015-11-08 15:52 UTC
In updating CheriBSD to use non-executable $c0 and non-writable $pcc, I encountered the following surprise:

```
static __inline __capability void *
cheri_codeptr(const void *ptr, size_t len)
{
#ifdef NOTYET
        __capability void (*c)(void) = ptr;
#else
        __capability void *c = cheri_setoffset(cheri_getpcc(),
            (register_t)ptr);
#endif

        /* Assume CFromPtr without base set, availability of CSetBounds. */
        return (cheri_csetbounds(c, len));
}

static __inline __capability void *
cheri_codeptrperm(const void *ptr, size_t len, register_t perm)
{

        return (cheri_andperm(cheri_codeptr(ptr, len),
            perm | CHERI_PERM_GLOBAL));
}
```

This is visible in compilations of ```cheritest```, and in particular, the function ```sandbox_class_load```:
````
        /*
         * Construct various class-related capabilities, such as the type,
         * code capability for the run-time linker, and code capability for
         * object-capability invocation.
         */
        sbcp->sbc_typecap = cheri_type_alloc();

        codecap = cheri_codeptrperm(sbcp->sbc_codemem, sbcp->sbc_codelen,
            CHERI_PERM_GLOBAL | CHERI_PERM_LOAD | CHERI_PERM_EXECUTE);
        codecap = cheri_setoffset(codecap, SANDBOX_RTLD_VECTOR);
        sbcp->sbc_classcap_rtld = cheri_seal(codecap, sbcp->sbc_typecap);

        codecap = cheri_codeptrperm(sbcp->sbc_codemem, sbcp->sbc_codelen,
            CHERI_PERM_GLOBAL | CHERI_PERM_LOAD | CHERI_PERM_EXECUTE);
        codecap = cheri_setoffset(codecap, SANDBOX_INVOKE_VECTOR);
        sbcp->sbc_classcap_invoke = cheri_seal(codecap, sbcp->sbc_typecap);

        return (0);
```

Without ```NOTYET```, the capabilities are explicitly derived from $pcc:
```
   120021820:   48000807        cgetpcc c1
   120021824:   49a10841        csetoffset      c1,c1,at
   120021828:   48210880        csetbounds      c1,c1,v0
   12002182c:   64010007        daddiu  at,zero,7
   120021830:   48810840        candperm        c1,c1,at
   120021834:   34018000        li      at,0x8000
   120021838:   49a20841        csetoffset      c2,c1,at
   12002183c:   484210c0        cseal   c2,c2,c3
   120021840:   660100e0        daddiu  at,s0,224
   120021844:   f8400800        csc     c2,at,0(c0)
   120021848:   34018200        li      at,0x8200
   12002184c:   49a10841        csetoffset      c1,c1,at
   120021850:   484108c0        cseal   c1,c1,c3
   120021854:   66010100        daddiu  at,s0,256
   120021858:   f8200800        csc     c1,at,0(c0)
```

With ```NOTYET```, the capabilities are derived from $c0 instead:
```
   1200217f0:   48810047        cfromptr        c1,c0,at
   1200217f4:   48210880        csetbounds      c1,c1,v0
   1200217f8:   64010007        daddiu  at,zero,7
   1200217fc:   48810840        candperm        c1,c1,at
   120021800:   34018000        li      at,0x8000
   120021804:   49a20841        csetoffset      c2,c1,at
   120021808:   484210c0        cseal   c2,c2,c3
   12002180c:   660100e0        daddiu  at,s0,224
   120021810:   f8400800        csc     c2,at,0(c0)
   120021814:   34018200        li      at,0x8200
   120021818:   49a10841        csetoffset      c1,c1,at
   12002181c:   484108c0        cseal   c1,c1,c3
   120021820:   66010100        daddiu  at,s0,256
   120021824:   f8200800        csc     c1,at,0(c0)
```

Use of CFromPtr as in the compiler-generated code is definitely preferable -- but relative to $pcc rather than $c0.

**Comment by davidchisnall** [comment] 2015-11-08 17:49
I think that this is expected.  The fact that it needs to be derived from `$pcc` is a property of the source type, not the destination.  If it's a data pointer, then it's relative to `$c0`, not to `$pcc`.  If you want it to be relative to `$pcc` then it should be cast to a function pointer first and then cast to a capability.

**Comment by davidchisnall** [comment] 2015-11-24 17:56
Ah, it looks as if the issue is a bit more subtly.  The variadic intrinsic takes an `i8*` (in AS0), so to fake it into working we cast the real target to the correct AS first.  The lifetime start and end intrinsics have the same problem and optimisation removes the redundant cast.  This means that we aren't seeing the original `alloca` when we get into SelectionDAG.  I'm not exactly sure what the correct fix is here.  (It might be that we have do actually do the right thing and make the `@llvm.va_start` intrinsic accept a pointer in a non-zero address space).

**Comment by davidchisnall** [comment] 2015-11-26 13:20
Ooops.  Didn't notice that this was filed as a clang bug.  It's an LLVM bug, which is now fixed.

**Comment by davidchisnall** [comment] 2015-11-26 13:22
Ooops, closed entirely the wrong issue.

**Closed** 2015-11-30 17:38 UTC
Labels: enhancement
