### ISSUE TITLE
Using unsupported -O options crashes clang

### ISSUE THREAD

**Issue by rwatson** [CTSRD-CHERI/clang#86] opened 2016-02-13 15:45 UTC
Due to a typo in a CheriBSD ```Makefile```, we are experience a Clang crash:
```
/home/rnw24/sdk/sdk/bin/clang -g -integrated-as --target=cheri-unknown-freebsd  -msoft-float --sysroot=/home/rnw24/obj/mips.mips64/home/rnw24/git/cheribsd/tmp -mabi=sandbox -mxgot -cheri-linker  -O2 -pipe -I/home/rnw24/git/cheribsd/lib/libjpeg -DNO_GETENV  -G0  -O20 -Wno-error  -std=gnu99 -Wsystem-headers -Werror -Wall -Wno-format-y2k -W -Wno-unused-parameter -Wstrict-prototypes -Wmissing-prototypes -Wpointer-arith -Wreturn-type -Wcast-qual -Wwrite-strings -Wswitch -Wshadow -Wunused-parameter -Wcast-align -Wchar-subscripts -Winline -Wnested-externs -Wredundant-decls -Wold-style-definition -Wno-pointer-sign -Wmissing-variable-declarations -Wthread-safety -Wno-empty-body -Wno-string-plus-int -Wno-unused-const-variable  -Qunused-arguments -Wno-unused-parameter -Wno-cast-qual -c /home/rnw24/git/cheribsd/lib/libjpeg/../../contrib/jpeg/jdmarker.c -o jdmarker.o
warning: optimization level '-O20' is not supported; using '-O3' instead
clang-3.8: error: unable to execute command: Segmentation fault (core dumped)
clang-3.8: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 3.8.0 (https://github.com/CTSRD-CHERI/clang 0a5302b5d63318045129da0e929f9114eba0264a) (http://github.com/CTSRD-CHERI/llvm 37973f7b9c8cc62bf4c06d4cfbb5c038c8d78618)
Target: cheri-unknown-freebsd
Thread model: posix
InstalledDir: /home/rnw24/sdk/sdk/bin
clang-3.8: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang-3.8: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-3.8: note: diagnostic msg: /tmp/jdmarker-33eb7e.c
clang-3.8: note: diagnostic msg: /tmp/jdmarker-33eb7e.sh
clang-3.8: note: diagnostic msg: 

********************
*** Error code 254
```

While the optimisation level is (```-O20```), in fact, an invalid one, it seems like the compiler should exit with an error rather than crash.

**Comment by rwatson** [comment] 2016-02-13 20:07
This relates to CheriBSD bug https://github.com/CTSRD-CHERI/cheribsd/issues/115

**Comment by davidchisnall** [comment] 2016-02-14 09:02
Can you attach the preprocessed source file that triggers this?  I can't reproduce it.  For me, clang just says:

```
warning: optimization level '-O20' is not supported; using '-O3' instead
```

I think that this bug is not what you think it is.  When `-O20` is specified, it is compiling at `-O3`.  We don't normally test above `-O2`, so you're likely hitting an optimiser that is not CHERI-aware, which is then crashing.

**Comment by davidchisnall** [comment] 2016-02-22 11:13
Closing, please open a new bug for the optimiser that is crashing, along with a test case.

**Closed by davidchisnall** 2016-02-22 11:13 UTC
Labels: bug
