### ISSUE TITLE
clang assertion on atomic_flag_clear_explicit

### ISSUE THREAD

**Issue by trasz** [CTSRD-CHERI/clang#119] opened 2017-03-01 13:35 UTC
LLVM branch merge-2017-01-18, looks like this:

```
fatal error: error in backend: Cannot select: 0x805a5a340: ch = AtomicStore<Volatile ST1[%17(addrspace=200)]> 0x805a5a4e0, 0x805a5a0d0, 0x805a5a410
  0x805a5a0d0: iFATPTR,ch = CopyFromReg 0x80583c8b0, Register:iFATPTR %vreg1
    0x805a5a750: iFATPTR = Register %vreg1
  0x805a5a410: i32,ch = load<LD1[%15(addrspace=200)], anyext from i8> 0x80583c8b0, 0x805a5a5b0, undef:iFATPTR
    0x805a5a5b0: iFATPTR,ch = CopyFromReg 0x80583c8b0, Register:iFATPTR %vreg0
      0x805a57c30: iFATPTR = Register %vreg0
    0x805a57af8: iFATPTR = undef
In function: atomic_flag_clear_explicit
```

To reproduce, build with "-mabi=sandbox  -target cheri-unknown-freebsd -c"; preprocessed test case attached.

[test-E.c.txt](https://github.com/CTSRD-CHERI/clang/files/810849/test-E.c.txt)

**Comment by davidchisnall** [comment] 2017-03-01 13:36
Please put test cases in a gist.

**Comment by davidchisnall** [comment] 2017-03-01 13:37
Duplicate of #118.  Was fixed before the bug report was filed.

**Closed by davidchisnall** 2017-03-01 13:37 UTC
Labels: bug, duplicate

**Comment by trasz** [comment] 2017-03-01 13:44
Erm, I'm still seeing the problem.

clang version 5.0.0 (https://github.com/CTSRD-CHERI/clang.git 335556b8170e39e6d720dcbda1d43a4533aee048) (https://github.com/CTSRD-CHERI/llvm.git 59e5c281cca155ac76ab834293b72fd6f8b81a42)

**Comment by davidchisnall** [comment] 2017-03-01 13:48
This is an LLVM bug.  It looks as if we're missing a pattern for a one-byte store.  Test case should be:

```
_Atomic(_Bool) obj;
void fail(void)
{
  obj = 1;
}
```
